# Generated by Django 6.0.5 on 2026-05-17 05:29

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('primer_apellido', models.TextField()),
                ('segundo_apellido', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'encargado',
                'verbose_name_plural': 'encargados',
                'db_table': 'encargados',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sala', models.IntegerField(unique=True)),
                ('capacidad', models.IntegerField(default=40)),
            ],
            options={
                'verbose_name': 'sala',
                'verbose_name_plural': 'salas',
                'db_table': 'salas',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('asistentes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField())),
                ('requerimientos', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True)),
                ('incidentes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True)),
                ('encargado', models.ForeignKey(db_column='encargado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.encargado')),
                ('sala', models.ForeignKey(db_column='sala_id', on_delete=django.db.models.deletion.CASCADE, to='reservas.sala')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'db_table': 'eventos',
            },
        ),
    ]
