# Generated by Django 6.0.5 on 2026-05-17 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encargado',
            old_name='primer_apellido',
            new_name='primerapellido',
        ),
        migrations.RenameField(
            model_name='encargado',
            old_name='segundo_apellido',
            new_name='segundoapellido',
        ),
    ]
