# Generated by Django 6.0.5 on 2026-05-25 21:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_rename_primer_apellido_encargado_primerapellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='incidentes',
        ),
        migrations.AddField(
            model_name='evento',
            name='reporte',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='evento',
            name='asistentes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='evento',
            name='encargado',
            field=models.TextField(blank=True, default=''),
        ),
    ]
