# Generated by Django 6.0.5 on 2026-05-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_remove_evento_incidentes_evento_reporte_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Encargado',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='asistentes',
        ),
        migrations.AddField(
            model_name='evento',
            name='asistentes',
            field=models.IntegerField(default=0),
        ),
    ]
